

development: &db
  adapter: mysql2
  encoding: utf8
  database: db_24832035n1
  username: user24832035n1
  password: cJfyaHwB
  host:     zeta.railshoster.de

test:
  <<: *db

  database: db_24832035n3
  username: user24832035n3
  password: Po5tp6ha
  host:     zeta.railshoster.de

production:
  <<: *db

  database: db_24832035n2
  username: user24832035n2
  password: fC1FDGOc
  host:     zeta.railshoster.de









